app = "node-service"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = 10

[http_service]
  internal_port = 8080
  force_https = true

  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 750
    hard_limit = 1000

  [[http_service.checks]]
    grace_period = "5s"
    interval = "10s"
    timeout = "5s"
    method = "GET"
    path = "/"

  [http_service.http_options.response.headers]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "0"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
